-- Create a table to store contact form submissions
-- Ensures schema exists to avoid ordering issues in CI runs

CREATE SCHEMA IF NOT EXISTS FIRST_SCHEMA;

CREATE TABLE IF NOT EXISTS FIRST_SCHEMA.CONTACT_SUBMISSIONS (
  SUBMISSION_ID STRING DEFAULT UUID_STRING() NOT NULL,
  FULL_NAME STRING NOT NULL,
  EMAIL STRING NOT NULL,
  PHONE STRING,
  SUBJECT STRING,
  MESSAGE STRING,
  CONSENT BOOLEAN DEFAULT FALSE,
  IP_ADDRESS STRING,
  USER_AGENT STRING,
  SOURCE_URL STRING,
  STATUS STRING DEFAULT 'new',
  SUBMITTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CONSTRAINT PK_CONTACT_SUBMISSIONS PRIMARY KEY (SUBMISSION_ID)
);

COMMENT ON TABLE FIRST_SCHEMA.CONTACT_SUBMISSIONS IS 'Stores contact form submissions from website/app users.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.SUBMISSION_ID IS 'Unique identifier (UUID) for the submission.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.FULL_NAME IS 'Full name of the submitter.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.EMAIL IS 'Email address of the submitter.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.PHONE IS 'Phone number of the submitter (optional).';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.SUBJECT IS 'Subject provided in the form (optional).';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.MESSAGE IS 'Message body submitted by the user.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.CONSENT IS 'True if the user consented to be contacted.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.IP_ADDRESS IS 'IP address captured at submission time.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.USER_AGENT IS 'User agent string from the client device.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.SOURCE_URL IS 'Page URL where the form was submitted.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.STATUS IS 'Processing status: new, reviewed, resolved, etc.';
COMMENT ON COLUMN FIRST_SCHEMA.CONTACT_SUBMISSIONS.SUBMITTED_AT IS 'Timestamp when the submission was created.';

