name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'migrations/**'
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_base.yml
    with:
      dry_run: false
    secrets: inherit
