name: Validate

on:
  pull_request:
    branches: [main]
    paths:
      - 'migrations/**'
      - 'terraform/**'
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/_base.yml
    with:
      dry_run: true
    secrets: inherit
